export interface Project {
	name: string;
	description: string;
	team?: boolean;
	stacks: string[];
	photo: string[];
	link?: string;
	slug?: string;
	as?: string;
}

export const projects: Project[] = [
	{
		name: "Talent Management Analysis",
		description:
			"intelligent analytical feature developed using a LLM with a Retrieval-Augmented Generation (RAG) approach to analyze data stored in the Human Resources system.",
		team: true,
		stacks: ["FastAPI", "Milvus", "LlamaIndex", "Paddle OCR", "LLM"],
		photo: ["hris-ai.jpg", "hris-ai-2.jpg", "hris-ai-3.jpg"],
		link: "https://hris-ai.oriens.my.id/docs",
		as: "AI Engineer",
	},
	{
		name: "Human Resources",
		description:
			"Digital platform developed to manage and streamline HR operations within organizations. This system help to handle employee data, recruitment process, work targets, retention analysis, leave management, and performance tracking. It also provides tools for training and development, performance appraisal, and employee feedback.",
		team: true,
		stacks: ["Nuxt", "Tailwind", "Express", "GraphQL"],
		photo: ["hris.jpg", "hris-2.jpg", "hris-3.jpg"],
		link: "https://hris.oriens.my.id",
		as: "Full Stack Developer",
	},
	{
		name: "Knowledge Management System",
		description:
			"Belajar bersama Badiklat Kemhan. Knowledge Management System adalah platform pembelajaran jarah jauh dan merdeka belajar online dari Badiklat Kemhan RI, yang membantu pengajar membuat diklat dan materi sehingga siswa dapat belajar di dalamnya.",
		team: true,
		stacks: ["Laravel", "Alpine JS"],
		photo: ["lms.png", "lms2.png", "lms3.png", "lms4.png", "lms5.png"],
		link: "https://lms-staging.oriens.my.id",
		as: "Full Stack Developer",
	},
	{
		name: "Oriens",
		description:
			"OriensCRM adalah productivity tools yang membantu tim dalam mengelola proyek, tugas, dan kolaborasi. Dengan fitur-fitur seperti manajemen job, pelacakan waktu, integrasi dengan berbagai aplikasi, automation, laporan analitik, dan lainnya.",
		team: true,
		stacks: ["Express", "Vue", "Vuetify", "Flutter", "GraphQL"],
		photo: ["oriens.png", "oriens2.png", "oriens3.png", "oriens4.png"],
		link: "https://dev.oriens.my.id",
		as: "Front End Developer, Mobile Flutter Developer",
	},
	{
		name: "Vitalmetrics",
		description: "Platform kalkulator BMI berbasis Internet of Things",
		team: false,
		stacks: ["Arduino", "Flutter"],
		photo: ["vitalmetrics.png"],
		as: "Backend Developer, IoT Engineer, Mobile Developer",
	},
	{
		name: "Midtown Hotel Apps",
		description:
			"Permudah pemesanan kamar untuk warga lokal dan juga turis untuk mencari hotel yang lokasi yang strategis di Surabaya, Jakarta, Samarinda, Balikpapan, dan Sampit.",
		team: false,
		stacks: ["Flutter"],
		photo: ["midtown.png"],
		as: "Mobile Flutter Developer",
	},
	{
		name: "Aset Tanah Polda",
		description: "Sistem pengelolaan tanah polda dan wilayah",
		team: false,
		stacks: ["Laravel"],
		photo: [
			"tanah-polda.png",
			"tanah-polda2.png",
			"tanah-polda3.png",
			"tanah-polda4.png",
			"tanah-polda5.png",
		],
		as: "Full Stack Developer",
	},
	{
		name: "Java Horoscope",
		description:
			"Web scrapping dan implementasi dari situs primbon.com menggunakan express.js, puppeteer, dan vue.js",
		team: false,
		stacks: ["Express", "Solid"],
		link: "https://java-horoscope.vercel.app",
		photo: ["java-horoscope.png", "java-horoscope2.png", "java-horoscope3.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Fermonitor",
		description:
			"Sistem identifikasi kematangan tapai singkong melalui kadar gas berbasis Internet of Things",
		team: false,
		stacks: ["Arduino", "Solid"],
		link: "https://www.youtube.com/watch?v=EkA_5Wfij40&t=363s",
		photo: [
			"fermonitor.png",
			"fermonitor2.png",
			"fermonitor3.png",
			"fermonitor4.png",
		],
		as: "Full Stack Developer, IoT Engineer",
	},
	{
		name: "KuyBisnis",
		description:
			"Tracking bisnis dari kelompok mahasiswa. Rencanakan kewirausahaan, kembangkan bisnis, dan ketahui hasil kegiatan bisnis berbasis web",
		team: false,
		stacks: ["Laravel"],
		photo: [
			"kuybisnis.jpg",
			"kuybisnis2.jpg",
			"kuybisnis3.jpg",
			"kuybisnis4.jpg",
		],
		as: "Full Stack Developer",
	},
	{
		name: "LostInfo",
		description:
			"Platform informasi pencarian dan pelaporan barang hilang. Dengan aplikasi ini penyebaran informasi mengenai barang hilang dan temuan menjadi lebih efektif. Fitur unggulan aplikasi ini adalah adanya perbandingan antara barang temuan dan barang hilang sehingga pengguna lebih menemukan barang miliknya dari barang yang serupa. Disediakan juga fitur lelang apabila tidak ada yang mengeklaim barang temuan user, selain itu user juga bisa melelang barang miliknya yang sudah tidak digunakan.",
		team: true,
		stacks: ["Laravel", "Solid", "Flutter"],
		photo: ["lostinfo.png", "lostinfo2.jpg", "lostinfo3.jpg", "lostinfo4.jpg"],
		as: "Full Stack Developer",
	},
	{
		name: "Rental Mobil",
		description:
			"Jasa layanan penyewaan dan rental mobil. Pengguna dapat mencari, memilih, dan memesan mobil yang sesuai dengan kebutuhan tanpa harus datang ke tempat sewa secara langsung",
		team: false,
		stacks: ["Laravel"],
		photo: ["rental-mobil.jpg", "rental-mobil2.jpg", "rental-mobil3.jpg"],
		as: "Full Stack Developer",
	},
	{
		name: "Arsogi Group",
		description: "Aplikasi katalog produk dan transaksi jual beli",
		link: "http://arsogigrup.com",
		team: false,
		stacks: ["Laravel", "Svelte"],
		photo: ["arsogi.png", "arsogi2.png", "arsogi3.png"],
		as: "Full Stack Developer",
	},
	{
		name: "E-Library",
		description: "Aplikasi untuk mengakses data peminjaman buku",
		team: false,
		stacks: ["Laravel", "Vue"],
		photo: ["e-library.png", "e-library2.png", "e-library3.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Pasar Online",
		description: "Pasar Online Tugas Akhir Pemrograman WEB",
		team: true,
		stacks: ["Codeigniter"],
		photo: ["pasaronline.png", "pasaronline2.png"],
		as: "Front End Developer",
	},
	{
		name: "Aset Desa Brebes",
		description: "Aset tanah PT MG INTERMEDIATAMA",
		link: "",
		team: true,
		stacks: ["Laravel", "Vue"],
		photo: ["asetdesa.png", "asetdesa2.png", "asetdesa3.png", "asetdesa4.png"],
		as: "Back End Developer",
	},
	{
		name: "Jurnal Mengajar",
		description: "Jurnal mengajar SMKN 2 Jember",
		link: "",
		team: false,
		stacks: ["Laravel", "React"],
		photo: ["jurnalmengajar.png", "jurnalmengajar2.png", "jurnalmengajar3.png"],
		as: "Full Stack Developer",
	},
	{
		name: "SPP SMK PGRI 5 Jember",
		description:
			"Sistem Informasi Aplikasi Pembayaran Sekolah SMK PGRI 5 Jember",
		team: true,
		stacks: ["CodeIgniter"],
		photo: ["sppsmk.png", "sppsmk2.png"],
		as: "Full Stack Developer",
	},
	{
		name: "PPDB SDUA",
		description: "Aplikasi Pendaftaran Siswa Baru SD Ummu Aiman",
		team: true,
		stacks: ["CodeIgniter"],
		photo: ["ppdb.png", "ppdb2.png"],
		as: "Front Stack Developer",
	},
	{
		name: "Perpustakaan",
		description: "Aplikasi E-Perpustakaan SDN Inpres Bhayangkara Kota Jayapura",
		team: true,
		stacks: ["CodeIgniter"],
		photo: ["perpustakaan.png", "perpustakaan2.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Siphuda",
		description:
			"Sistem Inventarisasi Produk Hukum Daerah Sekretariat DPRD Kabupaten Trenggalek",
		link: "https://siphuda.com",
		stacks: ["Laravel", "Svelte"],
		photo: ["siphuda.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Prima Usadha Jaya",
		description: "Aplikasi manajemen service bengkel",
		link: "https://primausadha.com",
		stacks: ["Laravel", "Svelte"],
		photo: ["bengkel.png", "bengkel2.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Administrasi Desa",
		description: "Aplikasi perantara keluhan rakyat desa",
		link: "",
		stacks: ["CodeIgniter"],
		photo: ["administrasi.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Tes Skripsi",
		description: "Aplikasi pengelolaan tes skripsi mahasiswa",
		team: true,
		link: "https://e-mta.fkm.untad.ac.id/",
		stacks: ["CodeIgniter"],
		photo: ["skripsi.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Shabab Aqiqah",
		description: "Aplikasi pengelolaan qurban & aqiqah",
		link: "http://shababaqiqah.com/",
		stacks: ["CodeIgniter"],
		photo: ["shababaqiqah.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Rumah Ibadah",
		description: "Aplikasi pencarian tempat ibadah suatu daerah",
		link: "",
		stacks: ["CodeIgniter", "React"],
		photo: ["rumah-ibadah.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Absen Petugas Masjid",
		description: "Aplikasi pengelolaan daftar hadir petugas masjid",
		link: "",
		stacks: ["Laravel", "React"],
		photo: ["absensi-masjid.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Smegrima Kelulusan",
		description: "Aplikasi cek kelulusan siswa SMK PGRI 05 Jember",
		team: true,
		link: "https://esemkaprima.com/kelulusan",
		stacks: ["CodeIgniter"],
		photo: ["kelulusan.png", "kelulusan2.png"],
		as: "Front End Developer",
	},
	{
		name: "Puskesmas",
		description: "Aplikasi pelayanan puskesmas Elly Uyo Adipura",
		link: "",
		stacks: ["CodeIgniter"],
		photo: ["rumah-sakit.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Zakat",
		description: "Aplikasi Manajemen Zakat Desa Ujong Gunong Rayeuk",
		link: "",
		stacks: ["CodeIgniter"],
		photo: ["zakat.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Direktori Biodata",
		description: "Aplikasi pengelolaan biodata pekerja",
		link: "",
		stacks: ["Codeigniter"],
		photo: ["direktori.png"],
		as: "Full Stack Developer",
	},
	{
		name: "PMB Uniyap",
		description: "Aplikasi pendaftaran mahasiswa baru Universitas Yapis Papua",
		link: "https://pmb-uniyap.com",
		stacks: ["Laravel", "Vue"],
		photo: ["pmb-uniyap.png", "pmb-uniyap2.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Pengajuan Beasiswa",
		description: "Aplikasi pengajaun beasiswa Poltas",
		link: "",
		stacks: ["CodeIgniter"],
		photo: ["beasiswa.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Pinjam Sarana",
		description: "Aplikasi peminjaman sarana sekolah",
		link: "",
		stacks: ["CodeIgniter"],
		photo: ["pinjam-sarana.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Absensi QRCode",
		description: "Aplikasi manajemen absensi berbasis QRcode",
		link: "",
		stacks: ["CodeIgniter"],
		photo: ["absensi-qrcode.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Sewa Kamar",
		description: "Aplikasi Penyewaan Kamar",
		link: "",
		stacks: ["CodeIgniter", "Vue"],
		photo: ["sewa-kamar.png", "sewa-kamar2.png"],
		as: "Full Stack Developer",
	},
	{
		name: "E-SPP",
		description: "Aplikasi pengelolaan pembayaran SPP",
		link: "",
		stacks: ["CodeIgniter"],
		photo: ["e-spp.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Prima Store",
		description: "Aplikasi market place kebutuhan siswa SMK PGRI 05 Jember",
		link: "",
		team: true,
		stacks: ["CodeIgniter"],
		photo: [
			"prima-store.png",
			"prima-store2.png",
			"prima-store3.png",
			"prima-store4.png",
		],
		as: "Full Stack Developer",
	},
	{
		name: "E-Kuisioner",
		description: "Aplikasi pelacakan alumni mahasiswa",
		link: "http://e-kuesioner.com",
		stacks: ["CodeIgniter"],
		photo: ["e-kuisioner.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Toko",
		description: "Aplikasi penjualan barang toko",
		link: "",
		stacks: ["CodeIgniter"],
		photo: ["toko.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Vicate",
		description: "Aplikasi manajemen sertifikat online",
		link: "http://vicate.org",
		stacks: ["CodeIgniter"],
		photo: ["vicate.png", "vicate2.png"],
		as: "Full Stack Developer",
	},
	{
		name: "Pilkada",
		description: "Aplikasi pemilihan ketua daerah",
		link: "",
		stacks: ["CodeIgniter"],
		photo: ["pilkada.png", "pilkada2.png"],
		as: "Full Stack Developer",
	},
].map((project: Project) => {
	project.slug = makeSlug(project.name);
	return project;
});
